package com.itis.homework.utils

object ParamsKeys {
    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
    const val ACTION_KEY = "TOAST_ACTION_KEY"
    const val SETTINGS_FRAGMENT_RESULT_KEY = "SETTINGS_FRAGMENT_RESULT_KEY"
    const val COROUTINES_FRAGMENT_RESULT_KEY = "COROUTINES_FRAGMENT_RESULT_KEY"
    const val IS_DETAIL_SETTING_KEY = "IS_DETAIL_SETTING_KEY"
    const val IS_HAVE_BUTTONS_SETTING_KEY = "IS_HAVE_BUTTONS_SETTING_KEY"
    const val IS_STOP_ON_BACKGROUND_SETTING_KEY = "IS_STOP_ON_BACKGROUND_SETTING_KEY"
    const val IMPORTANCE_SETTING_KEY = "IMPORTANCE_SETTING_KEY"
    const val VISIBILITY_SETTING_KEY = "VISIBILITY_SETTING_KEY"
}