package com.itis.homework

object ParamsKeys {
    const val FIRST_FRAGMENT_TITLE_KEY = "FIRST_FRAGMENT_TITLE_KEY"
    const val SECOND_FRAGMENT_TITLE_KEY = "SECOND_FRAGMENT_TITLE_KEY"
    const val THIRD_FRAGMENT_TITLE_KEY = "THIRD_FRAGMENT_TITLE_KEY"
    const val FIRST_FRAGMENT_EDIT_TEXT_TEXT_KEY = "FIRST_FRAGMENT_EDIT_TEXT_TEXT_KEY"
}